# SPDX-FileCopyrightText: 2026 Out of Control, Inc.
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = [".gitignore"]
SPDX-FileCopyrightText = "Out of Control Inc"
SPDX-License-Identifier = "MIT"
